
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri May 22 23:44:43 CST 2020
//----------------------------------------------------

package simpl.parser;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int CONS = 32;
  public static final int ORELSE = 19;
  public static final int GE = 31;
  public static final int UNIT = 34;
  public static final int LPAREN = 40;
  public static final int SEMI = 39;
  public static final int REF = 3;
  public static final int RPAREN = 41;
  public static final int REC = 6;
  public static final int NOT = 17;
  public static final int LT = 28;
  public static final int FN = 5;
  public static final int NIL = 2;
  public static final int PASS = 33;
  public static final int IN = 8;
  public static final int COMMA = 38;
  public static final int DIV = 23;
  public static final int NUM = 45;
  public static final int ASSIGN = 36;
  public static final int IF = 10;
  public static final int ID = 46;
  public static final int LE = 29;
  public static final int EOF = 0;
  public static final int STREAM = 4;
  public static final int APP = 44;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int MUL = 22;
  public static final int ADD = 20;
  public static final int MOD = 24;
  public static final int EQ = 26;
  public static final int ARROW = 35;
  public static final int NEG = 25;
  public static final int ELSE = 12;
  public static final int LSQUARE = 42;
  public static final int ANDALSO = 18;
  public static final int RSQUARE = 43;
  public static final int WHILE = 13;
  public static final int LET = 7;
  public static final int THEN = 11;
  public static final int NE = 27;
  public static final int END = 9;
  public static final int FALSE = 16;
  public static final int GT = 30;
  public static final int SUB = 21;
  public static final int DEREF = 37;
  public static final int DO = 14;
}

